%{
#include "hpp.hpp"
%}
%option noyywrap
%option yylineno
%%
#[^\n]*\n			{}					/* comment */
^\.end				{yyterminate();}	/* .end directive */

\(					TOC(Sym,LP)			/* brackets */
\)					TOC(Sym,RP)
\[					TOC(Sym,LQ)
\]					TOC(Sym,RQ)

\,					TOC(Sym,COMMA)		/* operators */
\=					TOC(Sym,EQ)
	
[a-z][a-zA-Z0-9_]*	TOC(Term,TERM)		/* term */
[A-Z][a-zA-Z0-9_]*	TOC(Var,VAR)		/* Variable */

[ \t\r\n]+			{}					/* drop spaces */
%%
